# Redirect with a 301
[[redirects]]
from = "/login"
to = "/login"
status = 200

# Redirect with a 302
[[redirects]]
from = "/register"
to = "/register"
status = 200

# Show a custom 404 for this path
[[redirects]]
from = "/dashboard"
to = "/dashboard"
status = 200

# Rewrite a path
[[redirects]]
from = "/pass-through"
to = "/index.html"
status = 200
